# Generated by Django 5.0.3 on 2024-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_remove_lesson_content_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
